=== DamjanSarlija/otvoreno_racunarstvo_lab1/schema.json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "$id": "https://or.fer.unizg.hr/studenci.json",
    "title": "OR Studenci",
    "description": "Skup podataka za izvođenje laboratorijskih vježbi iz predmeta Otvoreno računarstvo",
    "type": "array",
    "items": {
        "title": "Studenac",
        "description": "Poslovnica trgovine Studenac",
        "type": "object",
        "required": [
            "oznaka",
            "adresa",
            "mjesto",
            "geo_sirina",
            "geo_duzina",
            "ocjena",
            "broj_glasova",
            "otvaranje",
            "zatvaranje",
            "ima_zeleni_hell",
            "artikli"
        ],
        "properties": {
            "oznaka": {
                "title": "oznaka",
                "description": "Jedinstveni identifikator Studenac poslovnice naveden na službenoj internetskoj stranici Studenca",
                "type": "string"
            },
            "adresa": {
                "title": "adresa",
                "description": "Ulica i kućni broj poslovnice",
                "type": "string"
            },
            "mjesto": {
                "title": "mjesto",
                "description": "Naziv naselja u kojem se nalazi poslovnica",
                "type": "string"
            },
            "geo_sirina": {
                "title": "geo_sirina",
                "description": "Geografska širina lokacije poslovnice",
                "type": "number"
            },
            "geo_duzina": {
                "title": "geo_duzina",
                "description": "Geografska dužina lokacije poslovnice",
                "type": "number"
            },
            "ocjena": {
                "title": "ocjena",
                "description": "Prosječna ocjena dodijeljena lokaciji na Google kartama",
                "type": [
                    "integer",
                    "number"
                ]
            },
            "broj_glasova": {
                "title": "broj_glasova",
                "description": "Broj ocijena dodijeljenih lokaciji na Google kartama",
                "type": "integer"
            },
            "otvaranje": {
                "title": "otvaranje",
                "description": "Početak radnog vremena poslovnice radnim danom, ali ne nužno i nedjeljom",
                "type": "string"
            },
            "zatvaranje": {
                "title": "zatvaranje",
                "description": "Završetak radnog vremena poslovnice radnim danom, ali ne nužno i nedjeljom",
                "type": "string"
            },
            "ima_zeleni_hell": {
                "title": "ima_zeleni_hell",
                "description": "Označava nalazi li se trenutno u asortimanu poslovnice energetsko piće Hell Focus+",
                "type": "boolean"
            },
            "artikli": {
                "title": "artikli",
                "description": "Nekoliko artikala iz asortimana trgovine",
                "type": "array",
                "items": {
                    "title": "A Schema",
                    "description": "An explanation about the purpose of this instance.",
                    "type": "object",
                    "required": [
                        "naziv",
                        "cijena"
                    ],
                    "properties": {
                        "naziv": {
                            "title": "naziv",
                            "description": "Naziv artikla naveden u službenom katalogu Studenca pronađenom na službenoj internetskoj stranici Studenca",
                            "type": "string"
                        },
                        "cijena": {
                            "title": "cijena",
                            "description": "Trenutna cijena artikla navedena u službenom katalogu Studenca pronađenom na službenoj internetskoj stranici Studenca, može podrazumijevati i akcijsku cijenu ako je akcija trenutno u tijeku",
                            "type": "number"
                        }
                    }
                }
            }
        }
    }
}

=== DamjanSarlija/otvoreno_racunarstvo_lab1/studenci.json
[{"oznaka" : "T1162", "adresa" : "Vugrovečka cesta 62", "mjesto" : "Dobrodol", "geo_sirina" : 45.85434, "geo_duzina" : 16.11278, "ocjena" : 5, "broj_glasova" : 2, "otvaranje" : "7:00", "zatvaranje" : "21:00", "ima_zeleni_hell" : true, "artikli" : [{"naziv" : "Gazirana mineralna voda", "cijena" : 0.59}, {"naziv" : "Krem puding Galetta", "cijena" : 1.09}]}, {"oznaka" : "T876", "adresa" : "Zagrebačka cesta 9", "mjesto" : "Sesvete", "geo_sirina" : 45.82747, "geo_duzina" : 16.10799, "ocjena" : 3.7, "broj_glasova" : 31, "otvaranje" : "7:00", "zatvaranje" : "22:00", "ima_zeleni_hell" : false, "artikli" : [{"naziv" : "Pirovo integralno brašno", "cijena" : 1.89}]}, {"oznaka" : "T1160", "adresa" : "Bjelovarska ulica 2", "mjesto" : "Sesvete", "geo_sirina" : 45.82691, "geo_duzina" : 16.11117, "ocjena" : 5, "broj_glasova" : 3, "otvaranje" : "6:30", "zatvaranje" : "21:00", "ima_zeleni_hell" : true, "artikli" : [{"naziv" : "Tortilja", "cijena" : 1.89}, {"naziv" : "Šibice", "cijena" : 0.89}]}, {"oznaka" : "T1167", "adresa" : "Varaždinska cesta 90", "mjesto" : "Popovec", "geo_sirina" : 45.85068, "geo_duzina" : 16.14063, "ocjena" : 4.4, "broj_glasova" : 5, "otvaranje" : "7:00", "zatvaranje" : "21:00", "ima_zeleni_hell" : true, "artikli" : [{"naziv" : "Carska mješavina", "cijena" : 1.65}, {"naziv" : "Vitaminski napitak", "cijena" : 4.19}]}, {"oznaka" : "T1163", "adresa" : "Augusta Šenoe 49", "mjesto" : "Vugrovec", "geo_sirina" : 45.88053, "geo_duzina" : 16.10886, "ocjena" : 3.3, "broj_glasova" : 6, "otvaranje" : "6:30", "zatvaranje" : "21:00", "ima_zeleni_hell" : false, "artikli" : [{"naziv" : "Pašteta losos", "cijena" : 2.39}]}, {"oznaka" : "T1705", "adresa" : "Žugčićeva 22", "mjesto" : "Novoselec", "geo_sirina" : 45.84942, "geo_duzina" : 16.08261, "ocjena" : 5, "broj_glasova" : 1, "otvaranje" : "7:00", "zatvaranje" : "21:00", "ima_zeleni_hell" : false, "artikli" : [{"naziv" : "Osvježivač prostora", "cijena" : 3.99}, {"naziv" : "Panirani riblji štapići", "cijena" : 2.39}, {"naziv" : "Pašteta jetrena", "cijena" : 0.65}]}, {"oznaka" : "T1166", "adresa" : "Ulica kaktusa 5", "mjesto" : "Brestje", "geo_sirina" : 45.82746, "geo_duzina" : 16.08519, "ocjena" : 3.7, "broj_glasova" : 3, "otvaranje" : "7:00", "zatvaranje" : "21:00", "ima_zeleni_hell" : true, "artikli" : [{"naziv" : "Puding", "cijena" : 0.49}, {"naziv" : "Grah bijeli", "cijena" : 1.69}, {"naziv" : "Jabuka Idared", "cijena" : 1.27}]}, {"oznaka" : "T1415", "adresa" : "Oporovečki vinogradi 17", "mjesto" : "Oporovec", "geo_sirina" : 45.85384, "geo_duzina" : 16.0578, "ocjena" : 3, "broj_glasova" : 6, "otvaranje" : "7:00", "zatvaranje" : "22:00", "ima_zeleni_hell" : true, "artikli" : [{"naziv" : "Keks Choco cookie", "cijena" : 1.89}, {"naziv" : "Tjestenina filini", "cijena" : 0.98}, {"naziv" : "Grah šareni", "cijena" : 1.29}, {"naziv" : "Potpuna hrana za mačke", "cijena" : 0.65}, {"naziv" : "Ćevapčići", "cijena" : 8.99}, {"naziv" : "Mliječni napitak", "cijena" : 0.69}, {"naziv" : "Pečena šunka", "cijena" : 10.99}]}, {"oznaka" : "T1164", "adresa" : "Zagrebačka cesta 4C", "mjesto" : "Sesvete", "geo_sirina" : 45.82796, "geo_duzina" : 16.10796, "ocjena" : 5, "broj_glasova" : 1, "otvaranje" : "6:30", "zatvaranje" : "21:00", "ima_zeleni_hell" : true, "artikli" : [{"naziv" : "Čokolada ledena", "cijena" : 1.29}, {"naziv" : "Kikiriki", "cijena" : 1.29}, {"naziv" : "Četvrt mlade kokoši", "cijena" : 1.89}]}, {"oznaka" : "T1161", "adresa" : "Trg Antuna Mihanovića 4", "mjesto" : "Sesvete", "geo_sirina" : 45.8294, "geo_duzina" : 16.07957, "ocjena" : 4.8, "broj_glasova" : 6, "otvaranje" : "7:00", "zatvaranje" : "22:00", "ima_zeleni_hell" : false, "artikli" : [{"naziv" : "Kukuruz šećerac", "cijena" : 0.95}]}]
